# Generated by Django 3.0.5 on 2020-08-14 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('create_cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cvmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_color', models.IntegerField(blank=True)),
                ('cv_type', models.IntegerField(blank=True)),
                ('cv_img', models.ImageField(blank=True, upload_to='media/modelecv/')),
            ],
        ),
        migrations.AddField(
            model_name='diploma',
            name='m_intitule',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='m_poste',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_description', models.TextField(max_length=256)),
                ('m_date', models.DateTimeField(auto_now=True, null=True)),
                ('m_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_user_avatar', models.ImageField(blank=True, upload_to='media/createcv/')),
                ('m_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_nom', models.CharField(max_length=64)),
                ('m_niveau', models.CharField(max_length=64)),
                ('m_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Infoperso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_nom', models.CharField(blank=True, max_length=64, null=True)),
                ('m_prenom', models.CharField(blank=True, max_length=64, null=True)),
                ('m_villeresidence', models.CharField(blank=True, max_length=64, null=True)),
                ('m_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('m_age', models.IntegerField(default=0)),
                ('m_profession', models.CharField(default=' ', max_length=254)),
                ('m_telephone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, null=True)),
                ('m_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cvsetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create_cv.Cvmodel')),
                ('m_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cvfolder',
            name='m_infoperso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create_cv.Infoperso'),
        ),
        migrations.AddField(
            model_name='cvfolder',
            name='m_photos',
            field=models.ManyToManyField(blank=True, to='create_cv.Photo'),
        ),
        migrations.AddField(
            model_name='cvfolder',
            name='m_references',
            field=models.ManyToManyField(blank=True, to='create_cv.Reference'),
        ),
        migrations.AddField(
            model_name='cvfolder',
            name='m_setting',
            field=models.ManyToManyField(blank=True, to='create_cv.Cvsetting'),
        ),
    ]
