# Generated by Django 3.0.5 on 2021-02-16 18:30

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('create_cv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvmodel',
            name='cv_img',
        ),
        migrations.AddField(
            model_name='cvmodel',
            name='nom',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='cvmodel',
            name='cv_color',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='cvmodel',
            name='cv_type',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='infoperso',
            name='m_telephone',
            field=phone_field.models.PhoneField(blank=True, help_text='Numero de telephone', max_length=31, null=True),
        ),
        migrations.CreateModel(
            name='CvImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.ImageField(blank=True, upload_to='media/modelecv/')),
                ('m_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create_cv.Cvmodel')),
            ],
        ),
    ]
