# Generated by Django 3.0.5 on 2020-05-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_cv', '0002_diploma_m_intitule'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='m_poste',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
