# Generated by Django 2.2.14 on 2020-11-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_cv', '0002_auto_20200814_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvmodel',
            name='nom',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='cvmodel',
            name='cv_color',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='cvmodel',
            name='cv_type',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='infoperso',
            name='m_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='infoperso',
            name='m_profession',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
