# Generated by Django 3.0.5 on 2021-02-16 19:13

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('create_cv', '0002_auto_20210216_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoperso',
            name='m_telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Numero de telephone', max_length=128, null=True, region=None),
        ),
    ]
