# Generated by Django 2.2.7 on 2020-05-31 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('create_cv', '0003_experience_m_poste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infoperso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_nom', models.CharField(max_length=64)),
                ('m_prenom', models.CharField(blank=True, max_length=64, null=True)),
                ('m_villeresidence', models.CharField(max_length=64)),
                ('m_email', models.EmailField(max_length=254)),
                ('m_telephone', models.CharField(max_length=64)),
                ('m_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
