# Generated by Django 2.2.7 on 2020-06-06 09:28

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('create_cv', '0004_infoperso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoperso',
            name='m_nom',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='infoperso',
            name='m_telephone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
