# Generated by Django 2.2.7 on 2020-06-06 10:03

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('create_cv', '0005_auto_20200606_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoperso',
            name='m_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='infoperso',
            name='m_telephone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='infoperso',
            name='m_villeresidence',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
