# Generated by Django 3.0.5 on 2020-07-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_cv', '0012_auto_20200701_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvfolder',
            name='m_photos',
            field=models.ManyToManyField(blank=True, to='create_cv.Photo'),
        ),
    ]
