# Generated by Django 3.0.5 on 2020-07-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_cv', '0013_cvfolder_m_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='biographie',
            name='m_aide',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='competence',
            name='m_aide',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='cvfolder',
            name='m_aide',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='diploma',
            name='m_aide',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='m_aide',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='infoperso',
            name='m_aide',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='langue',
            name='m_aide',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='loisir',
            name='m_aide',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='m_aide',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
